### PR TITLE
UI/UX Prototype

### LINKED ISSUE #5: UI/UX Prototype

### PR DESCRIPTION
**Pull request by sdsantos**
Here is the UI/UX Prototype of the Stacks Auth Android App --> [FIGMA](https://www.figma.com/file/RQy9bq4EX4Pz4bWP9r01cQ/%F0%9F%93%B1-Blockstack-Auth-Android-App?node-id=95%3A0)

For those unfamiliar with the concept and purpose behind this app, you can read our [Stacks Grant proposal](https://github.com/stacksgov/Stacks-Grants/issues/22).

This UI/UX is based on the [Stacks Connect 2.0 WIP](https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/%F0%9F%93%90Connect?node-id=323%3A6793) from the Stacks UserX team.

The 2 main scenarios we cover are:
- **Fresh Install**: the user installed and used the Stacks Auth app by itself
- **From another app**: the user interacts with the Stacks Auth through another Android app that supports Stacks

We're still deciding on what to show first in the **Fresh Install** scenario. The two options we design are:
1) Ask the user to login/signup as the first thing. Afterwards, besides having the account managing features, show a Home screen with information about the Stacks ecosystem.
2) Start with the Home screen, plus a banner to login/signup, but we don't enforce it straight away.

We're leaning towards the second option. But we would like more feedback from the community on this matter.

The prototype covers does not cover all possible scenarios, but covers all unique screens. The missing flows can be deduced from this.

---

Closes #5

### CODE REVIEW

**Comment by psq** [comment]
I was under the impression that the stacks 2.0 tools wer using 24 words, not 12.  It seems to me being able to use the same passphrase that yields the same address across devices is really important.

And any plans to go beyond sign in like authorizing transactions from apps?

**Comment by sdsantos** [comment]
@psq Thanks for the feedback!

We copied the 12 words from the new Stacks Connect 2.0 design. But we'll double-check exactly what's the right pattern. We definitely want devices/apps to be interoperable.

There are some interesting possibilities after this initial version:
- Transaction signing (will become a big deal as the main net is rolled out, and it makes sense to go with the authenticator app)
- Digital wallet (but there are other community wallets being worked on, inclusive for Android
- Third-party app store (a decentralised alternative to the Google Play Store)

**Comment by markmhendrickson** [comment]
We plan to support both 12 and 24-word Secret Keys in the new versions of Connect and Stacks Wallet for Stacks 2.0, to facilitate the sort of interoperability indicated by @psq.

I would also suggest path #2 for the home screen here. It's generally good to require auth only for those experiences that need it.

**Comment by sdsantos** [comment]
It's settled then, we'll go with the scenario 2, which doesn't enforce login/signup straight away.

**Pull request merged**
